project:
  type: website
  resources:
    - "*.pdf"

website:
  title: "ZHAW LSFM Thesis Template Documentation"
  repo-url: https://github.com/zhaw-lsfm/quarto-thesis-docs
  repo-actions: [edit, source, issue]
  navbar:
    left:
      - href: index.qmd
        text: "Welcome"
      - text: "Getting Started"
        menu:
          - href: getting-started.qmd
            text: "With the template"
          - href: https://zhaw-adls.github.io/PA2-Quarto-Typst
            text: "With Quarto"
            target: _blank
      - manual.qmd
      - zhaw-requirements.qmd
      - text: "Template Demo"
        menu:
        - href: https://zhaw-lsfm.github.io/quarto-thesis/Robuste-Regression-und-Outlier-Erkennung.pdf
          text: "PDF (for submission)"
          target: _blank
        - href: https://zhaw-lsfm.github.io/quarto-thesis/
          text: "HTML (for development)"
          target: _blank
    right:
      - href: for-devs.qmd
        text: "For Developers / Contributors"
      - href: https://github.com/zhaw-lsfm/quarto-thesis/blob/main/CHANGELOG.md
        text: "Changelog"
        target: _blank
      - icon: github
        href: https://github.com/zhaw-lsfm/quarto-thesis
        text: "Template Repository"

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
